name: Build arm64 snap

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: checkout git repository
        uses: actions/checkout@v4

      - name: Build the snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 8.x/stable

    - name: Archive built snap
      run: |
        mkdir -p build_artifacts
        cp *.snap build_artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-snap
        path: build_artifacts/
